#!/usr/bin/bash

# run this script to configure dotfiles!
show_help() {
    echo "Usage: $0 [OPTIONS]"
    echo "Options:"
    echo "  -h, --help      Show this help message and exit."
    echo "  -l, --list      List dotfiles and exit."
    echo "  -a, --add 'cfg_fileobj_name' ./source \$HOME/destination."
    echo "                            Add a config file to be managed by dotfiles and exit."
    echo "  -r, --run       Run dotfiles."
}

CURRENT_DIR=$(pwd)
echo "Locating dir ..."
DOTFILE_PATH=$(find $HOME -type d -name ".dotfiles")
cd $DOTFILE_PATH || (echo "No .dotfiles directory found, place repo in sub directory ./home/some/path." && exit 1)
echo "      $dotfile_exec_path"

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            show_help
            exit 0
            ;;
        -l|--list)
            python3 -m dotfiles_manager list
            exit 0
            ;;
        -a|--add)
            shift
            config_name="$1"
            shift
            source="$1"
            shift
            destination="$1"
            python3 -m dotfiles_manager add "$config_name" "$source" "$destination"
            exit 0
            ;;
        -r|--run)
            python3 -m dotfiles_manager
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            show_help
            exit 1
            ;;
    esac
done

cd $CURRENT_DIR
exit 0